### ISSUE TITLE
New Age Theme

### ISSUE THREAD

**Issue by aoimedia** [jenstornell/kirby-themes#109]
**GitHub** https://github.com/TheSmithy/NewAge-KirbyCMS-Theme
**Live demo** https://blackrockdigital.github.io/startbootstrap-new-age

> **A bold and colorful Bootstrap landing page Kirby theme for web apps or other business use.**

![new_age_-_start_bootstrap_theme_-_2016-10-30_23 05 10](https://cloud.githubusercontent.com/assets/2782385/19840766/aaedab08-9ef5-11e6-8380-36e9d4e3d0f5.png)

**Comment by TheSmithy** [comment]
@aoimedia i deleted all my themes.

**Comment by aoimedia** [comment]
Sorry to hear, but thanks for the update.
