### ISSUE TITLE
Netly

### ISSUE THREAD

**Issue by wachilt** [jenstornell/kirby-themes#176]
**Details** https://gumroad.com/l/RJNHc
**Live demo** http://themes.kueker.net/netly

> **Netly is build for creating powerful websites without touching any code. That means it comes with a PageBuilder and 20+ different modules out of the box and more are coming soon. Simple add a module (e.g. banners, price lists, latest articles) to your page and create your own individual look for any page.**

![screen shot 2018-05-22 at 14 06 24-fullpage](https://user-images.githubusercontent.com/2782385/40364259-c6c9a1da-5dc9-11e8-869f-962484b81ca4.png)

**Comment by timpulver** [comment]
@wachilt Both websites are down.
