### ISSUE TITLE
Modèle 3345 Theme

### ISSUE THREAD

**Issue by aoimedia** [jenstornell/kirby-themes#60]
**GitHub** https://github.com/constantinjoly/3345
**Details** https://gumroad.com/l/kPoXt#
**Live demo** http://kc.konstantin.fr/3345

> **Modèle 3345 is a simple, minimal Kirby theme for personal websites, blogs & portfolios.**

![3345_website_home_-_2016-03-09_22 33 08](https://cloud.githubusercontent.com/assets/2782385/13652974/0788c90a-e647-11e5-96d0-9429e27761ca.png)

**Comment by cleverdream** [comment]
Github link is no longer available.

**Comment by aoimedia** [comment]
@cleverdream Thanks for the heads-up.
3345 Theme is no longer available.
Now closed.
